ITEM.name = "Document Folder"
ITEM.description = "A folder for organizing documents."
ITEM.model = "models/props_lab/binderblue.mdl"
ITEM.category = "Containers"
ITEM.base = "base_document_container"
ITEM.width = 2
ITEM.height = 2
ITEM.invWidth = 25
ITEM.invHeight = 10
ITEM.containerLabel = "folder"
